### ISSUE TITLE
Consider using `:erlang.phash2/1` as the hash function

### ISSUE THREAD

**Issue by tanguilp** [derekkraan/merkle_map#1]
If requirements are met, consider using `:erlang.phash2/1` as the hash function which works on any erlang term.

It allows removing the Murmur dependency.

Note that it doesn't have a uniform output:
```elixir
iex(9)> :erlang.phash2(:a)              
97
iex(10)> :erlang.phash2(:b)          
98
```
Not sure whether it's a problem or not.

**Comment by derekkraan** [comment]
That would be a problem, yes. It needs to return consistent values, otherwise we will get a lot of false-positives, and keys being sorted into the wrong buckets.

**Comment by derekkraan** [comment]
Actually ... it might even be an advantage ... The resulting merkle tree would be denser than if you used a hash function that distributed hashes evenly.

**Comment by derekkraan** [comment]
Turns out `:erlang.phash2` is about twice as fast according to my benchmarks... Thanks for the suggestion! :tada:
