### ISSUE TITLE
Question about map.put vs map.merge

### ISSUE THREAD

**Issue by vans163** [derekkraan/merkle_map#6]
The benchmarks show map_put is faster than merge, but Jose said put calls merge under the hood https://elixirforum.com/t/at-which-point-should-i-use-map-merge/19503/2.

I wonder how accurate that is?

**Comment by derekkraan** [comment]
Hi,

If you look in the benchmark file, you'll notice that the Map.put benchmark is not doing the same thing as the Map.merge benchmark. So I think José's claim is quite accurate.

Cheers

**Comment by vans163** [comment]
Quite inaccurate you mean?  He claimed there Map.put and Map.merge are identical at the instruction level. But your benchmark here shows something totally different.  Unless maybe its a multi_key merge vs a single key merge?

Anyways inappropriate for a issue but I have no idea how to reach you otherwise :P

Would love to chat more about delta crdt, if your in IRC, discord, etc?

**Comment by derekkraan** [comment]
That's right, the benchmark for map_put and map_merge are doing two different things:

map_put - put one value
map_merge - merge two big maps that differ by just one key

I'm in the [Elixir Slack](https://elixir-slackin.herokuapp.com/), there is a channel for #horde.
